-- This file is generated by the pre-processor on 2024-04-21 17:53:20
-- Please do not do not modify this file!
Script.actor="BackgroundMenu"

Script.fadeoutspeed=0.008 --float  "Fadeout Speed"

--[[ Inputs ]]--
--[[ Outputs ]]--
function Script:Outputs()
end
