-- This file is generated by the pre-processor on 2024-05-05 21:39:27
-- Please do not do not modify this file!
Script.actor="ClientCameraTest"
Script.lookat=nil --entity "Look At"

--[[ Inputs ]]--
--[[ Outputs ]]--
function Script:Outputs()
end
