-- This file is generated by the pre-processor on 2024-05-18 18:36:42
-- Please do not do not modify this file!
Script.actor="FirstPersonControls"

Script.croucheyeheight=0.64 --float croucheyeheight

Script.eyeheight=1.35 --float eyeheight
Script.allowspinning=true --bool allowspinning
Script.allowzooming=true --bool allowzooming

--[[ Inputs ]]--
--[[ Outputs ]]--
function Script:Outputs()
end
