-- This file is generated by the pre-processor on 2024-04-28 19:03:55
-- Please do not do not modify this file!
Script.actor="FirstPersonControls"

Script.eyeheight=1.7 --float eyeheight

Script.jumpforce=8.0 --float jumpforce

Script.jumplunge=1.5 --float jumplunge
--exposed_float croucheyeheight = 1.0f;

--exposed_float croucheyeheight = 1.0f;
Script.movespeed=4.0 --float movespeed
Script.allowspinning=true --bool allowspinning
Script.allowzooming=true --bool allowzooming

--[[ Inputs ]]--
--[[ Outputs ]]--
function Script:Outputs()
end
