// This file is generated by the pre-processor on 2024-04-02 03:13:21
// Please do not do not modify this file!
#pragma once
#include "pch.h"
using namespace Leadwerks;

#include "Actors/Test/Spinner.h"

static void RegisterActors(Leadwerks::Entity* entity)
{
	ATTACH_ENTITY_TO_ACTOR(entity,Spinner);
}
