// This file is generated by the pre-processor on 2024-05-18 18:36:42
// Please do not do not modify this file!
#pragma once
#include "pch.h"
using namespace Leadwerks;

#include "Actors/Camera/BackgroundMenu.h"
#include "Actors/Camera/ClientCameraTest.h"
#include "Actors/Player/FirstPersonControls.h"
#include "Actors/Test/Spinner.h"

static void RegisterActors(Leadwerks::Entity* entity)
{
	ATTACH_ENTITY_TO_ACTOR(entity,BackgroundMenu);
	ATTACH_ENTITY_TO_ACTOR(entity,ClientCameraTest);
	ATTACH_ENTITY_TO_ACTOR(entity,FirstPersonControls);
	ATTACH_ENTITY_TO_ACTOR(entity,Spinner);
}
